source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CRToastSwift_Example', :exclusive => true do
  pod "CRToastSwift", :path => "../"
end

target 'CRToastSwift_Tests', :exclusive => true do
  pod "CRToastSwift", :path => "../"

  
end
