source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'CRToastSwift_Example' do
  pod "CRToastSwift", :path => "../"
end

target 'CRToastSwift_Tests' do
  pod "CRToastSwift", :path => "../"
end
  
# Xcode 7.1 workaround
post_install do |installer|
    `find Pods -regex 'Pods/CRToast.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)CRToast\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end

